version: "3.7"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./static:/app/static

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: